name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Tests
        run: go test ./... 

      - name: Build Binary
        run: go build -o web-scanner main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-scanner
          path: web-scanner
